entry:
  - ./src/specs
  - ./test/specs
port: 3030

proxy:
  /graphql: http://localhost:4000

images:
  baseUrl: /my-images
  dir: example/image-path/images

build:
  prod: false
  outputFolder: ./.build/my-folder
  modules:
    main: ./src/client/ui-harness.js
    single:
      - ./src/components/GlobalStyles.jsx
      - ./src/components/util.js
  vendor:
    - react
    - react-dom

cssModules: 
  - .module.css
  - .mcss
